### ISSUE TITLE
Can't find 'action.yml'

### ISSUE THREAD

**Issue by MuYunyun** [yi-Xu-0100/traffic-to-badge#21]
this is my [traffic2badge.yml](https://github.com/MuYunyun/blog/blob/master/.github/workflows/traffic2badge.yml)

when run this action, it throws an error as follow, [link](https://github.com/MuYunyun/blog/actions/runs/326872730)

![image](https://user-images.githubusercontent.com/19354791/97099246-f29ff300-16c1-11eb-915b-eff18087fe0d.png)

what's the problem, please help.

**Comment by yi-Xu-0100** [comment]
Oh, I found that you just use the example that `.github/workflows/traffic2badge.yaml` from [traffic-to-badge](https://github.com/yi-Xu-0100/traffic-to-badge). This example will test the main branch of `traffic-to-badge` repo. So in that I use the follow code:

```yaml
      - name: Get Traffic
        id: traffic
        uses: ./
        with:
          my_token: ${{ secrets.TRAFFIC_TOKEN }}
          #(default) static_list: ${{ github.repository }}
          #(default) traffic_branch: traffic
          #(default) views_color: brightgreen
          #(default) clones_color: brightgreen
          #(default) logo: github
```

For your personal usage, just follow the README suggestion:

```yaml
      - name: Get Traffic
        id: traffic
        uses: yi-Xu-0100/traffic-to-badge@v1.1.4
        with:
          my_token: ${{ secrets.TRAFFIC_TOKEN }}
          #(default) static_list: ${{ github.repository }}
          #(default) traffic_branch: traffic
          #(default) views_color: brightgreen
          #(default) clones_color: brightgreen
          #(default) logo: github
```

And if you want to make badges for more repos, I advise for using the template repo.
